pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {
        stage('packer_version') {
            steps {
                sh 'packer --version' 
            }
        }

        stage('aws_version') {
            steps {
                sh 'aws --version' 
            }
        }

        stage('packer_init') {
            steps {
                dir('Packer/instance'){
                    sh 'packer init .'
                } 
            }
        }

        stage('packer_format') {
            steps {
                dir('Packer/instance'){
                    sh 'packer fmt .'
                }
            }
        }

        stage('packer_validate') {
            steps {
                dir('Packer/instance'){
                    sh 'packer validate .'
                }
            }
        }

        stage('packer_build') {
            parallel {
                stage('build_amazon_linux'){
                    steps {
                        dir('Packer/instance'){
                            sh 'packer build ami-amazon-linux.pkr.hcl'
                        }
                    }
                }
                stage('build_ubuntu_linux'){
                    steps {
                        dir('Packer/instance'){
                            sh 'packer build ami-ubuntu-linux.pkr.hcl'
                        }
                    }
                }
            }
        }
    }
}
