pipeline {
    agent any

    stages {
        stage('Stage_01') {
            steps {
                sh 'echo Stage Passed' 
            }
        }

        stage('Stage_02') {
            steps {
                sh 'echo Stage Passed'
            }
        }
    }
}
